[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "jaxloop"
author = "The jaxloop authors"
author-email = "jaxloop-team@google.com"
requires = ["clu"]
